/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.food.portal.model.impl;

import com.food.portal.model.ItemRequest;
import com.food.portal.model.ItemRequestModel;
import com.food.portal.model.ItemRequestSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ItemRequest service. Represents a row in the &quot;FOOD_ItemRequest&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ItemRequestModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ItemRequestImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ItemRequestImpl
 * @generated
 */
@JSON(strict = true)
public class ItemRequestModelImpl
	extends BaseModelImpl<ItemRequest> implements ItemRequestModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a item request model instance should use the <code>ItemRequest</code> interface instead.
	 */
	public static final String TABLE_NAME = "FOOD_ItemRequest";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"requestId", Types.BIGINT},
		{"itemName", Types.VARCHAR}, {"quantity", Types.INTEGER},
		{"metric", Types.VARCHAR}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"status", Types.INTEGER},
		{"statusByUserId", Types.BIGINT}, {"statusByUserName", Types.VARCHAR},
		{"statusDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("requestId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("itemName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("quantity", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("metric", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table FOOD_ItemRequest (uuid_ VARCHAR(75) null,requestId LONG not null primary key,itemName VARCHAR(75) null,quantity INTEGER,metric VARCHAR(75) null,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table FOOD_ItemRequest";

	public static final String ORDER_BY_JPQL =
		" ORDER BY itemRequest.createDate ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY FOOD_ItemRequest.createDate ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long STATUS_COLUMN_BITMASK = 4L;

	public static final long USERID_COLUMN_BITMASK = 8L;

	public static final long UUID_COLUMN_BITMASK = 16L;

	public static final long CREATEDATE_COLUMN_BITMASK = 32L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static ItemRequest toModel(ItemRequestSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		ItemRequest model = new ItemRequestImpl();

		model.setUuid(soapModel.getUuid());
		model.setRequestId(soapModel.getRequestId());
		model.setItemName(soapModel.getItemName());
		model.setQuantity(soapModel.getQuantity());
		model.setMetric(soapModel.getMetric());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setStatus(soapModel.getStatus());
		model.setStatusByUserId(soapModel.getStatusByUserId());
		model.setStatusByUserName(soapModel.getStatusByUserName());
		model.setStatusDate(soapModel.getStatusDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<ItemRequest> toModels(ItemRequestSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<ItemRequest> models = new ArrayList<ItemRequest>(
			soapModels.length);

		for (ItemRequestSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public ItemRequestModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _requestId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setRequestId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _requestId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ItemRequest.class;
	}

	@Override
	public String getModelClassName() {
		return ItemRequest.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ItemRequest, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ItemRequest, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ItemRequest, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ItemRequest)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ItemRequest, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ItemRequest, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ItemRequest)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ItemRequest, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ItemRequest, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, ItemRequest>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			ItemRequest.class.getClassLoader(), ItemRequest.class,
			ModelWrapper.class);

		try {
			Constructor<ItemRequest> constructor =
				(Constructor<ItemRequest>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<ItemRequest, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ItemRequest, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ItemRequest, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<ItemRequest, Object>>();
		Map<String, BiConsumer<ItemRequest, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<ItemRequest, ?>>();

		attributeGetterFunctions.put("uuid", ItemRequest::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<ItemRequest, String>)ItemRequest::setUuid);
		attributeGetterFunctions.put("requestId", ItemRequest::getRequestId);
		attributeSetterBiConsumers.put(
			"requestId",
			(BiConsumer<ItemRequest, Long>)ItemRequest::setRequestId);
		attributeGetterFunctions.put("itemName", ItemRequest::getItemName);
		attributeSetterBiConsumers.put(
			"itemName",
			(BiConsumer<ItemRequest, String>)ItemRequest::setItemName);
		attributeGetterFunctions.put("quantity", ItemRequest::getQuantity);
		attributeSetterBiConsumers.put(
			"quantity",
			(BiConsumer<ItemRequest, Integer>)ItemRequest::setQuantity);
		attributeGetterFunctions.put("metric", ItemRequest::getMetric);
		attributeSetterBiConsumers.put(
			"metric", (BiConsumer<ItemRequest, String>)ItemRequest::setMetric);
		attributeGetterFunctions.put("groupId", ItemRequest::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<ItemRequest, Long>)ItemRequest::setGroupId);
		attributeGetterFunctions.put("companyId", ItemRequest::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<ItemRequest, Long>)ItemRequest::setCompanyId);
		attributeGetterFunctions.put("userId", ItemRequest::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<ItemRequest, Long>)ItemRequest::setUserId);
		attributeGetterFunctions.put("userName", ItemRequest::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<ItemRequest, String>)ItemRequest::setUserName);
		attributeGetterFunctions.put("createDate", ItemRequest::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<ItemRequest, Date>)ItemRequest::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", ItemRequest::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<ItemRequest, Date>)ItemRequest::setModifiedDate);
		attributeGetterFunctions.put("status", ItemRequest::getStatus);
		attributeSetterBiConsumers.put(
			"status", (BiConsumer<ItemRequest, Integer>)ItemRequest::setStatus);
		attributeGetterFunctions.put(
			"statusByUserId", ItemRequest::getStatusByUserId);
		attributeSetterBiConsumers.put(
			"statusByUserId",
			(BiConsumer<ItemRequest, Long>)ItemRequest::setStatusByUserId);
		attributeGetterFunctions.put(
			"statusByUserName", ItemRequest::getStatusByUserName);
		attributeSetterBiConsumers.put(
			"statusByUserName",
			(BiConsumer<ItemRequest, String>)ItemRequest::setStatusByUserName);
		attributeGetterFunctions.put("statusDate", ItemRequest::getStatusDate);
		attributeSetterBiConsumers.put(
			"statusDate",
			(BiConsumer<ItemRequest, Date>)ItemRequest::setStatusDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getRequestId() {
		return _requestId;
	}

	@Override
	public void setRequestId(long requestId) {
		_requestId = requestId;
	}

	@JSON
	@Override
	public String getItemName() {
		if (_itemName == null) {
			return "";
		}
		else {
			return _itemName;
		}
	}

	@Override
	public void setItemName(String itemName) {
		_itemName = itemName;
	}

	@JSON
	@Override
	public int getQuantity() {
		return _quantity;
	}

	@Override
	public void setQuantity(int quantity) {
		_quantity = quantity;
	}

	@JSON
	@Override
	public String getMetric() {
		if (_metric == null) {
			return "";
		}
		else {
			return _metric;
		}
	}

	@Override
	public void setMetric(String metric) {
		_metric = metric;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_columnBitmask = -1L;

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_columnBitmask |= STATUS_COLUMN_BITMASK;

		if (!_setOriginalStatus) {
			_setOriginalStatus = true;

			_originalStatus = _status;
		}

		_status = status;
	}

	public int getOriginalStatus() {
		return _originalStatus;
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		_statusDate = statusDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(ItemRequest.class.getName()));
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), ItemRequest.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ItemRequest toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ItemRequest>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ItemRequestImpl itemRequestImpl = new ItemRequestImpl();

		itemRequestImpl.setUuid(getUuid());
		itemRequestImpl.setRequestId(getRequestId());
		itemRequestImpl.setItemName(getItemName());
		itemRequestImpl.setQuantity(getQuantity());
		itemRequestImpl.setMetric(getMetric());
		itemRequestImpl.setGroupId(getGroupId());
		itemRequestImpl.setCompanyId(getCompanyId());
		itemRequestImpl.setUserId(getUserId());
		itemRequestImpl.setUserName(getUserName());
		itemRequestImpl.setCreateDate(getCreateDate());
		itemRequestImpl.setModifiedDate(getModifiedDate());
		itemRequestImpl.setStatus(getStatus());
		itemRequestImpl.setStatusByUserId(getStatusByUserId());
		itemRequestImpl.setStatusByUserName(getStatusByUserName());
		itemRequestImpl.setStatusDate(getStatusDate());

		itemRequestImpl.resetOriginalValues();

		return itemRequestImpl;
	}

	@Override
	public int compareTo(ItemRequest itemRequest) {
		int value = 0;

		value = DateUtil.compareTo(
			getCreateDate(), itemRequest.getCreateDate());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ItemRequest)) {
			return false;
		}

		ItemRequest itemRequest = (ItemRequest)obj;

		long primaryKey = itemRequest.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		ItemRequestModelImpl itemRequestModelImpl = this;

		itemRequestModelImpl._originalUuid = itemRequestModelImpl._uuid;

		itemRequestModelImpl._originalGroupId = itemRequestModelImpl._groupId;

		itemRequestModelImpl._setOriginalGroupId = false;

		itemRequestModelImpl._originalCompanyId =
			itemRequestModelImpl._companyId;

		itemRequestModelImpl._setOriginalCompanyId = false;

		itemRequestModelImpl._originalUserId = itemRequestModelImpl._userId;

		itemRequestModelImpl._setOriginalUserId = false;

		itemRequestModelImpl._setModifiedDate = false;

		itemRequestModelImpl._originalStatus = itemRequestModelImpl._status;

		itemRequestModelImpl._setOriginalStatus = false;

		itemRequestModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ItemRequest> toCacheModel() {
		ItemRequestCacheModel itemRequestCacheModel =
			new ItemRequestCacheModel();

		itemRequestCacheModel.uuid = getUuid();

		String uuid = itemRequestCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			itemRequestCacheModel.uuid = null;
		}

		itemRequestCacheModel.requestId = getRequestId();

		itemRequestCacheModel.itemName = getItemName();

		String itemName = itemRequestCacheModel.itemName;

		if ((itemName != null) && (itemName.length() == 0)) {
			itemRequestCacheModel.itemName = null;
		}

		itemRequestCacheModel.quantity = getQuantity();

		itemRequestCacheModel.metric = getMetric();

		String metric = itemRequestCacheModel.metric;

		if ((metric != null) && (metric.length() == 0)) {
			itemRequestCacheModel.metric = null;
		}

		itemRequestCacheModel.groupId = getGroupId();

		itemRequestCacheModel.companyId = getCompanyId();

		itemRequestCacheModel.userId = getUserId();

		itemRequestCacheModel.userName = getUserName();

		String userName = itemRequestCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			itemRequestCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			itemRequestCacheModel.createDate = createDate.getTime();
		}
		else {
			itemRequestCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			itemRequestCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			itemRequestCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		itemRequestCacheModel.status = getStatus();

		itemRequestCacheModel.statusByUserId = getStatusByUserId();

		itemRequestCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = itemRequestCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			itemRequestCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			itemRequestCacheModel.statusDate = statusDate.getTime();
		}
		else {
			itemRequestCacheModel.statusDate = Long.MIN_VALUE;
		}

		return itemRequestCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ItemRequest, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ItemRequest, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ItemRequest, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((ItemRequest)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<ItemRequest, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<ItemRequest, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ItemRequest, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((ItemRequest)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ItemRequest>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _requestId;
	private String _itemName;
	private int _quantity;
	private String _metric;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private int _status;
	private int _originalStatus;
	private boolean _setOriginalStatus;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private long _columnBitmask;
	private ItemRequest _escapedModel;

}